# Generated by Django 3.2.7 on 2021-12-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
