# Generated by Django 3.2.7 on 2021-12-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todo_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
